### ISSUE TITLE
New Style="height" feature

### ISSUE THREAD

**Issue by shawnpaw** [byuweb/byu-hero-banner#17]
New Style="height" feature does not seem to work on class="side-image"

**Comment by michaelpratt28** [comment]
@shawnpaw Can you take a screenshot of what you are seeing on your end? Also can you be a little more specific with what doesn't seem to be working? Thanks

**Comment by shawnpaw** [comment]
![hero height issue 2](https://user-images.githubusercontent.com/32400433/36039962-45ddece0-0d81-11e8-8cc5-3edd76eac7f9.png)
![hero height issue](https://user-images.githubusercontent.com/32400433/36039965-4607332a-0d81-11e8-9df7-1d38fdc69ce5.png)

**Comment by michaelpratt28** [comment]
@shawnpaw I apologize, but I'm still not seeing any issues. Your image has the browser console covering half of the hero-banner and it's not your code I'm looking for. Can you explain to me what the problem is?

**Comment by shawnpaw** [comment]
Yes, the image with my console open is showing 559 pixels in height, the other image is showing that I set the hero to have a height of 480pixels using your style="height" addition. 

I've tried this feature on all other hero classes and it seems to work perfectly except the "side-image" class.

**Comment by michaelpratt28** [comment]
Your console is showing that your image has a **width** of 559 pixels and a **height** of 414 pixels.

**Comment by shawnpaw** [comment]
Haha. You are right. Either way it is not matching the style height I added. I wasn't sure if this was a design choice or a bug. Just pointing it out.

**Comment by shawnpaw** [comment]
Wait. When I view the container computed height, it is 480. I was not taking into consideration the white space. it is working. Sorry. I'll see if I can close this. Sorry.

**Comment by michaelpratt28** [comment]
No problem! Happy to help. Feel free to reach out if you have any further questions.
