### ISSUE TITLE
Hero "right" class issue

### ISSUE THREAD

**Issue by shawnpaw** [byuweb/byu-hero-banner#18]
When using the "right" class on a hero image block in the hero region and then adding a block in the hero region after it. The second block after the hero block covers over the top of the hero block. When you remove the class "right" from the hero block the two blocks play nicely together again.

![hero right class 2](https://user-images.githubusercontent.com/32400433/36041681-91a42702-0d86-11e8-8acb-2529288f7bc3.png)
![hero right class 3](https://user-images.githubusercontent.com/32400433/36041683-91c6b25e-0d86-11e8-8bc7-20d0ebd42fae.png)
![hero right class](https://user-images.githubusercontent.com/32400433/36041684-91e93680-0d86-11e8-9174-3dbf964a7bd6.png)

**Comment by kebowdog** [comment]
Is this on a server with a public URL so we can take a look at the generated HTML? My gut feeling is that this is a drupal issue, since we're using the "right" class without any issues on https://mlbean.byu.edu/, but I'd need to see the page to make sure.

**Comment by shawnpaw** [comment]
I removed the  “Right” to get everything happy again. I can put it back Monday if you would like to see it on our site www-2018-d1.groups.et.byu.net. I can put the two block together no problem. It is when I add the class “right” that things get weird. Let me know. Have a great weekend.

Shawn Ward
CAEDM Windows Systems Admin
801-422-8120

**Comment by kebowdog** [comment]
Ok, I found the problem. Your drupal styles are interfering with the banner. The file http://www-2018-d1.groups.et.byu.net/sites/default/files/css/css_jhQyLwMyOIUswz8ekdNvjfLKIAgGVKQD20BkpoxjuQE.css is applying a "float: right !important" to anything with the "right" class. I'll have @michaelpratt28 add an alternate name for that "right" class (something like "hero-right-align" that's less likely to run into conflicts. In the meantime you can override the float right as a workaround.

**Comment by shawnpaw** [comment]
Awesome. Thanks!

**Comment by kebowdog** [comment]
Fixed in PR #19

**Comment by shawnpaw** [comment]
Just tested it. Works great now. Thanks!
